# Generated by Django 6.0.6 on 2026-06-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='year',
        ),
        migrations.AddField(
            model_name='experience',
            name='department',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.IntegerField(default=2026),
        ),
        migrations.AddField(
            model_name='experience',
            name='faculty',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(),
        ),
    ]
