# Generated by Django 6.0.6 on 2026-06-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_experience_description_remove_experience_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_avalible',
            new_name='is_available',
        ),
    ]
