databases:
  - name: portfolio-db
    plan: free
    databaseName: portfolio
    user: portfolio_user

services:
  # Django — main portfolio site
  - type: web
    name: oleksiienko-portfolio
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "cd portfolio && gunicorn portfolio.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: FASTAPI_URL
        value: "https://portfolio-fastapi-uk5o.onrender.com"

  # FastAPI — contact form API
  - type: web
    name: portfolio-fastapi
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd portfolio && uvicorn fastapi_service.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.12.7"
      - key: CORS_ORIGINS
        value: "https://portfolio-django-2h9f.onrender.com,https://oleksiienko-portfolio.onrender.com"
